<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="re" nsURI="http://www.polarsys.org/capella/common/re/7.0.0"
    nsPrefix="re">
  <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ReAbstractElement" abstract="true" eSuperTypes="platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReNamedElement" abstract="true" eSuperTypes="#//ReAbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReDescriptionElement" abstract="true"
      eSuperTypes="#//ReNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReElementContainer" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1"
        eType="#//CatalogElement" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatalogElementPkg" eSuperTypes="#//ReNamedElement #//ReElementContainer">
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElementPkgs" upperBound="-1"
        eType="#//CatalogElementPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecCatalog" eSuperTypes="#//CatalogElementPkg platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value="http://www.polarsys.org/capella/core/modeller/7.0.0#//SystemEngineering "/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraintMapping">
      <details key="Mapping" value="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaModeller.ecore#//SystemEngineering "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCompliancyDefinitionPkg"
        eType="#//CompliancyDefinitionPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupingElementPkg" eSuperTypes="#//CatalogElementPkg platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value="http://www.polarsys.org/capella/core/modeller/7.0.0#//SystemEngineering http://www.polarsys.org/capella/core/cs/7.0.0#//BlockArchitecture"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatalogElementLink" eSuperTypes="#//ReAbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//CatalogElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//CatalogElementLink"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsynchronizedFeatures"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffixed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatalogElement" eSuperTypes="#//ReDescriptionElement #//ReElementContainer">
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CatalogElementKind"
        defaultValueLiteral="REC">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//CatalogElement">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentCompliancy" eType="#//CompliancyDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultReplicaCompliancy"
        eType="#//CompliancyDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLinks" upperBound="-1"
        eType="#//CatalogElementLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedElements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedLinks.target"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replicatedElements" upperBound="-1"
        eType="#//CatalogElement" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="origin"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="retrieve all referencing elements which have the current element as origin"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CatalogElementKind">
    <eLiterals name="REC" literal="REC"/>
    <eLiterals name="RPL" value="1" literal="RPL"/>
    <eLiterals name="REC_RPL" value="2" literal="REC_RPL"/>
    <eLiterals name="GROUPING" value="3" literal="GROUPING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompliancyDefinitionPkg" eSuperTypes="#//ReNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefinitions" upperBound="-1"
        eType="#//CompliancyDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompliancyDefinition" eSuperTypes="#//ReDescriptionElement">
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
  </eClassifiers>
</ecore:EPackage>
