/*******************************************************************************
 * Copyright (c) 2006, 2020 THALES GLOBAL SERVICES.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 * 
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Thales - initial API and implementation
 *******************************************************************************/
package org.polarsys.capella.core.data.pa.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.polarsys.capella.common.data.activity.AbstractActivity;
import org.polarsys.capella.common.data.activity.ActivityGroup;
import org.polarsys.capella.common.data.activity.ActivityPackage;
import org.polarsys.capella.common.data.activity.util.ActivitySwitch;
import org.polarsys.capella.core.data.capellamodeller.provider.CapellaModellerEditPlugin;
import org.polarsys.capella.core.data.pa.PaFactory;
import org.polarsys.capella.core.data.pa.PaPackage;
import org.polarsys.capella.core.data.pa.util.PaAdapterFactory;
import org.polarsys.kitalpha.emde.extension.ModelExtensionHelper;
import org.polarsys.kitalpha.emde.extension.edit.ChildCreationExtenderManager;
import org.polarsys.kitalpha.emde.model.edit.provider.NewChildDescriptorHelper;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PaItemProviderAdapterFactory extends PaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
	/**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
   * This helps manage the child creation extenders.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(CapellaModellerEditPlugin.INSTANCE, PaPackage.eNS_URI);

	/**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
   * This constructs an instance.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public PaItemProviderAdapterFactory() {
    supportedTypes.add(IEditingDomainItemProvider.class);
    supportedTypes.add(IStructuredItemContentProvider.class);
    supportedTypes.add(ITreeItemContentProvider.class);
    supportedTypes.add(IItemLabelProvider.class);
    supportedTypes.add(IItemPropertySource.class);
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalArchitecturePkg} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalArchitecturePkgItemProvider physicalArchitecturePkgItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalArchitecturePkg}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalArchitecturePkgAdapter() {
    if (physicalArchitecturePkgItemProvider == null) {
      physicalArchitecturePkgItemProvider = new PhysicalArchitecturePkgItemProvider(this);
    }

    return physicalArchitecturePkgItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalArchitecture} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalArchitectureItemProvider physicalArchitectureItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalArchitecture}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalArchitectureAdapter() {
    if (physicalArchitectureItemProvider == null) {
      physicalArchitectureItemProvider = new PhysicalArchitectureItemProvider(this);
    }

    return physicalArchitectureItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalFunction} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalFunctionItemProvider physicalFunctionItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalFunction}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalFunctionAdapter() {
    if (physicalFunctionItemProvider == null) {
      physicalFunctionItemProvider = new PhysicalFunctionItemProvider(this);
    }

    return physicalFunctionItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalFunctionPkg} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalFunctionPkgItemProvider physicalFunctionPkgItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalFunctionPkg}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalFunctionPkgAdapter() {
    if (physicalFunctionPkgItemProvider == null) {
      physicalFunctionPkgItemProvider = new PhysicalFunctionPkgItemProvider(this);
    }

    return physicalFunctionPkgItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalComponent} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalComponentItemProvider physicalComponentItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalComponent}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalComponentAdapter() {
    if (physicalComponentItemProvider == null) {
      physicalComponentItemProvider = new PhysicalComponentItemProvider(this);
    }

    return physicalComponentItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalComponentPkg} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalComponentPkgItemProvider physicalComponentPkgItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalComponentPkg}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalComponentPkgAdapter() {
    if (physicalComponentPkgItemProvider == null) {
      physicalComponentPkgItemProvider = new PhysicalComponentPkgItemProvider(this);
    }

    return physicalComponentPkgItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.PhysicalNode} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PhysicalNodeItemProvider physicalNodeItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.PhysicalNode}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPhysicalNodeAdapter() {
    if (physicalNodeItemProvider == null) {
      physicalNodeItemProvider = new PhysicalNodeItemProvider(this);
    }

    return physicalNodeItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.LogicalArchitectureRealization} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected LogicalArchitectureRealizationItemProvider logicalArchitectureRealizationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.LogicalArchitectureRealization}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createLogicalArchitectureRealizationAdapter() {
    if (logicalArchitectureRealizationItemProvider == null) {
      logicalArchitectureRealizationItemProvider = new LogicalArchitectureRealizationItemProvider(this);
    }

    return logicalArchitectureRealizationItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.pa.LogicalInterfaceRealization} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected LogicalInterfaceRealizationItemProvider logicalInterfaceRealizationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.pa.LogicalInterfaceRealization}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createLogicalInterfaceRealizationAdapter() {
    if (logicalInterfaceRealizationItemProvider == null) {
      logicalInterfaceRealizationItemProvider = new LogicalInterfaceRealizationItemProvider(this);
    }

    return logicalInterfaceRealizationItemProvider;
  }

	/**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
    return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
  }

	/**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
    this.parentAdapterFactory = parentAdapterFactory;
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public boolean isFactoryForType(Object type) {
    return supportedTypes.contains(type) || super.isFactoryForType(type);
  }

	/**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
    return super.adapt(notifier, this);
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Object adapt(Object object, Object type) {
    if (isFactoryForType(type)) {
      Object adapter = super.adapt(object, type);
      if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
        return adapter;
      }
    }

    return null;
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public List<IChildCreationExtender> getChildCreationExtenders() {
    return childCreationExtenderManager.getChildCreationExtenders();
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
    return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public ResourceLocator getResourceLocator() {
    return childCreationExtenderManager;
  }

	/**
   * This adds a listener.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.addListener(notifyChangedListener);
  }

	/**
   * This removes a listener.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.removeListener(notifyChangedListener);
  }

	/**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void fireNotifyChanged(Notification notification) {
    changeNotifier.fireNotifyChanged(notification);

    if (parentAdapterFactory != null) {
      parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

	/**
   * This disposes all of the item providers created by this factory. 
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void dispose() {
    if (physicalArchitecturePkgItemProvider != null) physicalArchitecturePkgItemProvider.dispose();
    if (physicalArchitectureItemProvider != null) physicalArchitectureItemProvider.dispose();
    if (physicalFunctionItemProvider != null) physicalFunctionItemProvider.dispose();
    if (physicalFunctionPkgItemProvider != null) physicalFunctionPkgItemProvider.dispose();
    if (physicalComponentItemProvider != null) physicalComponentItemProvider.dispose();
    if (physicalComponentPkgItemProvider != null) physicalComponentPkgItemProvider.dispose();
    if (physicalNodeItemProvider != null) physicalNodeItemProvider.dispose();
    if (logicalArchitectureRealizationItemProvider != null) logicalArchitectureRealizationItemProvider.dispose();
    if (logicalInterfaceRealizationItemProvider != null) logicalInterfaceRealizationItemProvider.dispose();
  }

	/**
   * A child creation extender for the {@link ActivityPackage}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public static class ActivityChildCreationExtender implements IChildCreationExtender {
		/**
     * The switch for creating child descriptors specific to each extended class.
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		protected static class CreationSwitch extends ActivitySwitch<Object> {
			/**
       * The child descriptors being populated.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected List<Object> newChildDescriptors;

			/**
       * The domain in which to create the children.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected EditingDomain editingDomain;

			/**
       * Creates the a switch for populating child descriptors in the given domain.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
        this.newChildDescriptors = newChildDescriptors;
        this.editingDomain = editingDomain;
      }
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseAbstractActivity(AbstractActivity object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/pa/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ABSTRACT_ACTIVITY__OWNED_NODES,
                         PaFactory.eINSTANCE.createPhysicalFunction());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseActivityGroup(ActivityGroup object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/pa/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_GROUP__OWNED_NODES,
                         PaFactory.eINSTANCE.createPhysicalFunction());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected CommandParameter createChildParameter(Object feature, Object child) {
        return new CommandParameter(null, feature, child);
      }

		}

		/**
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
      ArrayList<Object> result = new ArrayList<Object>();
      new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
      return result;
    }

		/**
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		public ResourceLocator getResourceLocator() {
      return CapellaModellerEditPlugin.INSTANCE;
    }
	}

}
