/*******************************************************************************
 * Copyright (c) 2006, 2020 THALES GLOBAL SERVICES.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 * 
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Thales - initial API and implementation
 *******************************************************************************/
package org.polarsys.capella.core.data.information.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.edit.command.CommandParameter;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.polarsys.capella.common.data.activity.ActivityEdge;
import org.polarsys.capella.common.data.activity.ActivityPackage;
import org.polarsys.capella.common.data.activity.ObjectNode;
import org.polarsys.capella.common.data.activity.ValuePin;
import org.polarsys.capella.common.data.activity.util.ActivitySwitch;
import org.polarsys.capella.common.data.modellingcore.AbstractConstraint;
import org.polarsys.capella.common.data.modellingcore.AbstractParameter;
import org.polarsys.capella.common.data.modellingcore.AbstractParameterSet;
import org.polarsys.capella.common.data.modellingcore.ModellingcorePackage;
import org.polarsys.capella.common.data.modellingcore.util.ModellingcoreSwitch;
import org.polarsys.capella.core.data.capellamodeller.provider.CapellaModellerEditPlugin;
import org.polarsys.capella.core.data.information.InformationFactory;
import org.polarsys.capella.core.data.information.InformationPackage;
import org.polarsys.capella.core.data.information.util.InformationAdapterFactory;
import org.polarsys.kitalpha.emde.extension.ModelExtensionHelper;
import org.polarsys.kitalpha.emde.extension.edit.ChildCreationExtenderManager;
import org.polarsys.kitalpha.emde.model.edit.provider.NewChildDescriptorHelper;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class InformationItemProviderAdapterFactory extends InformationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
	/**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
   * This helps manage the child creation extenders.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(CapellaModellerEditPlugin.INSTANCE, InformationPackage.eNS_URI);

	/**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
   * This constructs an instance.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public InformationItemProviderAdapterFactory() {
    supportedTypes.add(IEditingDomainItemProvider.class);
    supportedTypes.add(IStructuredItemContentProvider.class);
    supportedTypes.add(ITreeItemContentProvider.class);
    supportedTypes.add(IItemLabelProvider.class);
    supportedTypes.add(IItemPropertySource.class);
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Association} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected AssociationItemProvider associationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Association}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createAssociationAdapter() {
    if (associationItemProvider == null) {
      associationItemProvider = new AssociationItemProvider(this);
    }

    return associationItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Class} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ClassItemProvider classItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Class}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createClassAdapter() {
    if (classItemProvider == null) {
      classItemProvider = new ClassItemProvider(this);
    }

    return classItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Collection} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected CollectionItemProvider collectionItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Collection}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createCollectionAdapter() {
    if (collectionItemProvider == null) {
      collectionItemProvider = new CollectionItemProvider(this);
    }

    return collectionItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.CollectionValue} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected CollectionValueItemProvider collectionValueItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.CollectionValue}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createCollectionValueAdapter() {
    if (collectionValueItemProvider == null) {
      collectionValueItemProvider = new CollectionValueItemProvider(this);
    }

    return collectionValueItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.CollectionValueReference} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected CollectionValueReferenceItemProvider collectionValueReferenceItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.CollectionValueReference}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createCollectionValueReferenceAdapter() {
    if (collectionValueReferenceItemProvider == null) {
      collectionValueReferenceItemProvider = new CollectionValueReferenceItemProvider(this);
    }

    return collectionValueReferenceItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.DataPkg} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected DataPkgItemProvider dataPkgItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.DataPkg}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createDataPkgAdapter() {
    if (dataPkgItemProvider == null) {
      dataPkgItemProvider = new DataPkgItemProvider(this);
    }

    return dataPkgItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.DomainElement} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected DomainElementItemProvider domainElementItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.DomainElement}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createDomainElementAdapter() {
    if (domainElementItemProvider == null) {
      domainElementItemProvider = new DomainElementItemProvider(this);
    }

    return domainElementItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.KeyPart} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected KeyPartItemProvider keyPartItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.KeyPart}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createKeyPartAdapter() {
    if (keyPartItemProvider == null) {
      keyPartItemProvider = new KeyPartItemProvider(this);
    }

    return keyPartItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.OperationAllocation} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected OperationAllocationItemProvider operationAllocationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.OperationAllocation}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createOperationAllocationAdapter() {
    if (operationAllocationItemProvider == null) {
      operationAllocationItemProvider = new OperationAllocationItemProvider(this);
    }

    return operationAllocationItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Parameter} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ParameterItemProvider parameterItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Parameter}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createParameterAdapter() {
    if (parameterItemProvider == null) {
      parameterItemProvider = new ParameterItemProvider(this);
    }

    return parameterItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Property} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PropertyItemProvider propertyItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Property}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPropertyAdapter() {
    if (propertyItemProvider == null) {
      propertyItemProvider = new PropertyItemProvider(this);
    }

    return propertyItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Service} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ServiceItemProvider serviceItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Service}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createServiceAdapter() {
    if (serviceItemProvider == null) {
      serviceItemProvider = new ServiceItemProvider(this);
    }

    return serviceItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Union} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected UnionItemProvider unionItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Union}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createUnionAdapter() {
    if (unionItemProvider == null) {
      unionItemProvider = new UnionItemProvider(this);
    }

    return unionItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.UnionProperty} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected UnionPropertyItemProvider unionPropertyItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.UnionProperty}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createUnionPropertyAdapter() {
    if (unionPropertyItemProvider == null) {
      unionPropertyItemProvider = new UnionPropertyItemProvider(this);
    }

    return unionPropertyItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.Unit} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected UnitItemProvider unitItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.Unit}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createUnitAdapter() {
    if (unitItemProvider == null) {
      unitItemProvider = new UnitItemProvider(this);
    }

    return unitItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.PortRealization} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PortRealizationItemProvider portRealizationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.PortRealization}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPortRealizationAdapter() {
    if (portRealizationItemProvider == null) {
      portRealizationItemProvider = new PortRealizationItemProvider(this);
    }

    return portRealizationItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.PortAllocation} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected PortAllocationItemProvider portAllocationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.PortAllocation}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createPortAllocationAdapter() {
    if (portAllocationItemProvider == null) {
      portAllocationItemProvider = new PortAllocationItemProvider(this);
    }

    return portAllocationItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.ExchangeItem} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ExchangeItemItemProvider exchangeItemItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.ExchangeItem}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createExchangeItemAdapter() {
    if (exchangeItemItemProvider == null) {
      exchangeItemItemProvider = new ExchangeItemItemProvider(this);
    }

    return exchangeItemItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.ExchangeItemElement} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ExchangeItemElementItemProvider exchangeItemElementItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.ExchangeItemElement}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createExchangeItemElementAdapter() {
    if (exchangeItemElementItemProvider == null) {
      exchangeItemElementItemProvider = new ExchangeItemElementItemProvider(this);
    }

    return exchangeItemElementItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.ExchangeItemInstance} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ExchangeItemInstanceItemProvider exchangeItemInstanceItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.ExchangeItemInstance}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createExchangeItemInstanceAdapter() {
    if (exchangeItemInstanceItemProvider == null) {
      exchangeItemInstanceItemProvider = new ExchangeItemInstanceItemProvider(this);
    }

    return exchangeItemInstanceItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.InformationRealization} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected InformationRealizationItemProvider informationRealizationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.InformationRealization}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createInformationRealizationAdapter() {
    if (informationRealizationItemProvider == null) {
      informationRealizationItemProvider = new InformationRealizationItemProvider(this);
    }

    return informationRealizationItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link org.polarsys.capella.core.data.information.ExchangeItemRealization} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ExchangeItemRealizationItemProvider exchangeItemRealizationItemProvider;

	/**
   * This creates an adapter for a {@link org.polarsys.capella.core.data.information.ExchangeItemRealization}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createExchangeItemRealizationAdapter() {
    if (exchangeItemRealizationItemProvider == null) {
      exchangeItemRealizationItemProvider = new ExchangeItemRealizationItemProvider(this);
    }

    return exchangeItemRealizationItemProvider;
  }

	/**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
    return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
  }

	/**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
    this.parentAdapterFactory = parentAdapterFactory;
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public boolean isFactoryForType(Object type) {
    return supportedTypes.contains(type) || super.isFactoryForType(type);
  }

	/**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
    return super.adapt(notifier, this);
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Object adapt(Object object, Object type) {
    if (isFactoryForType(type)) {
      Object adapter = super.adapt(object, type);
      if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
        return adapter;
      }
    }

    return null;
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public List<IChildCreationExtender> getChildCreationExtenders() {
    return childCreationExtenderManager.getChildCreationExtenders();
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
    return childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public ResourceLocator getResourceLocator() {
    return childCreationExtenderManager;
  }

	/**
   * This adds a listener.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.addListener(notifyChangedListener);
  }

	/**
   * This removes a listener.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.removeListener(notifyChangedListener);
  }

	/**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void fireNotifyChanged(Notification notification) {
    changeNotifier.fireNotifyChanged(notification);

    if (parentAdapterFactory != null) {
      parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

	/**
   * This disposes all of the item providers created by this factory. 
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public void dispose() {
    if (associationItemProvider != null) associationItemProvider.dispose();
    if (classItemProvider != null) classItemProvider.dispose();
    if (collectionItemProvider != null) collectionItemProvider.dispose();
    if (collectionValueItemProvider != null) collectionValueItemProvider.dispose();
    if (collectionValueReferenceItemProvider != null) collectionValueReferenceItemProvider.dispose();
    if (dataPkgItemProvider != null) dataPkgItemProvider.dispose();
    if (domainElementItemProvider != null) domainElementItemProvider.dispose();
    if (keyPartItemProvider != null) keyPartItemProvider.dispose();
    if (operationAllocationItemProvider != null) operationAllocationItemProvider.dispose();
    if (parameterItemProvider != null) parameterItemProvider.dispose();
    if (propertyItemProvider != null) propertyItemProvider.dispose();
    if (serviceItemProvider != null) serviceItemProvider.dispose();
    if (unionItemProvider != null) unionItemProvider.dispose();
    if (unionPropertyItemProvider != null) unionPropertyItemProvider.dispose();
    if (unitItemProvider != null) unitItemProvider.dispose();
    if (portRealizationItemProvider != null) portRealizationItemProvider.dispose();
    if (portAllocationItemProvider != null) portAllocationItemProvider.dispose();
    if (exchangeItemItemProvider != null) exchangeItemItemProvider.dispose();
    if (exchangeItemElementItemProvider != null) exchangeItemElementItemProvider.dispose();
    if (exchangeItemInstanceItemProvider != null) exchangeItemInstanceItemProvider.dispose();
    if (informationRealizationItemProvider != null) informationRealizationItemProvider.dispose();
    if (exchangeItemRealizationItemProvider != null) exchangeItemRealizationItemProvider.dispose();
  }

	/**
   * A child creation extender for the {@link ModellingcorePackage}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public static class ModellingcoreChildCreationExtender implements IChildCreationExtender {
		/**
     * The switch for creating child descriptors specific to each extended class.
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		protected static class CreationSwitch extends ModellingcoreSwitch<Object> {
			/**
       * The child descriptors being populated.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected List<Object> newChildDescriptors;

			/**
       * The domain in which to create the children.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected EditingDomain editingDomain;

			/**
       * Creates the a switch for populating child descriptors in the given domain.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
        this.newChildDescriptors = newChildDescriptors;
        this.editingDomain = editingDomain;
      }
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseAbstractConstraint(AbstractConstraint object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/information/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_CONSTRAINT__OWNED_SPECIFICATION,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_CONSTRAINT__OWNED_SPECIFICATION,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseAbstractParameter(AbstractParameter object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/information/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_PARAMETER__RATE,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_PARAMETER__RATE,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_PARAMETER__PROBABILITY,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_PARAMETER__PROBABILITY,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseAbstractParameterSet(AbstractParameterSet object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/information/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_PARAMETER_SET__PROBABILITY,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ModellingcorePackage.Literals.ABSTRACT_PARAMETER_SET__PROBABILITY,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected CommandParameter createChildParameter(Object feature, Object child) {
        return new CommandParameter(null, feature, child);
      }

		}

		/**
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
      ArrayList<Object> result = new ArrayList<Object>();
      new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
      return result;
    }

		/**
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		public ResourceLocator getResourceLocator() {
      return CapellaModellerEditPlugin.INSTANCE;
    }
	}

	/**
   * A child creation extender for the {@link ActivityPackage}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public static class ActivityChildCreationExtender implements IChildCreationExtender {
		/**
     * The switch for creating child descriptors specific to each extended class.
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		protected static class CreationSwitch extends ActivitySwitch<Object> {
			/**
       * The child descriptors being populated.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected List<Object> newChildDescriptors;

			/**
       * The domain in which to create the children.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected EditingDomain editingDomain;

			/**
       * Creates the a switch for populating child descriptors in the given domain.
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
        this.newChildDescriptors = newChildDescriptors;
        this.editingDomain = editingDomain;
      }
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseActivityEdge(ActivityEdge object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/information/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__RATE,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__RATE,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__PROBABILITY,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__PROBABILITY,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__GUARD,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__GUARD,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__WEIGHT,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.ACTIVITY_EDGE__WEIGHT,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseObjectNode(ObjectNode object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/information/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.OBJECT_NODE__UPPER_BOUND,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.OBJECT_NODE__UPPER_BOUND,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			@Override
			public Object caseValuePin(ValuePin object) {
        // begin-extension-code
        if (ModelExtensionHelper.getInstance(object).isExtensionModelDisabled(EcoreUtil.getRootContainer(object).eClass().getEPackage().getNsURI(), "http://www.polarsys.org/capella/core/information/7.0.0")) { //$NON-NLS-1$
          return null;				
        }
        // end-extension-code
                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.VALUE_PIN__VALUE,
                         InformationFactory.eINSTANCE.createCollectionValue());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



                // begin-extension-code
                {
                    CommandParameter commandParameter = createChildParameter
                        (ActivityPackage.Literals.VALUE_PIN__VALUE,
                         InformationFactory.eINSTANCE.createCollectionValueReference());
                    if (NewChildDescriptorHelper.isValidCommand(object, commandParameter)) {
                        newChildDescriptors.add(commandParameter);      
                    }
                }
                // end-extension-code



        return null;
      }
 
			/**
       * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
       * @generated
       */
			protected CommandParameter createChildParameter(Object feature, Object child) {
        return new CommandParameter(null, feature, child);
      }

		}

		/**
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
      ArrayList<Object> result = new ArrayList<Object>();
      new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
      return result;
    }

		/**
     * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
     * @generated
     */
		public ResourceLocator getResourceLocator() {
      return CapellaModellerEditPlugin.INSTANCE;
    }
	}

}
