<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="layout" nsURI="http://org.polarsys.capella.layout" nsPrefix="layout">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramLayout" eSuperTypes="#//ISemanticLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLayouts" upperBound="-1"
        eType="#//ILayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliedLayers" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronized" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILayout" abstract="true" interface="true"
      eSuperTypes="platform:/plugin/org.eclipse.sirius.model/model/viewpoint.ecore#//DRefreshable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISemanticLayout" abstract="true" interface="true"
      eSuperTypes="#//ILayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualMapping" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliedFilters" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliedStyles" upperBound="-1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeLayout" eSuperTypes="#//ISemanticLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ISemanticLayout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ISemanticLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeLayout" eSuperTypes="#//ISemanticLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bounds" eType="#//Bounds"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLayouts" upperBound="-1"
        eType="#//ILayout" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoteLayout" eSuperTypes="#//ISemanticLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bounds" eType="#//Bounds"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SessionLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLayouts" upperBound="-1"
        eType="#//DiagramLayout" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bounds" eSuperTypes="#//Location #//Size"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relative" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Size">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
</ecore:EPackage>
