/*******************************************************************************
 * Copyright (c) 2006, 2017 THALES GLOBAL SERVICES.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *    Thales - initial API and implementation
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.23 at 05:43:10 PM IST 
//

package org.polarsys.capella.common.tools.report.config.persistence;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LogLevel" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="outputName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "logLevel" })
@XmlRootElement(name = "OutputConfiguration")
public class OutputConfiguration implements Cloneable {

  @XmlElement(name = "LogLevel", required = true)
  protected List<LogLevel> logLevel;
  @XmlAttribute(required = true)
  protected String outputName;

  /**
   * Gets the value of the logLevel property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the logLevel property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getLogLevel().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link LogLevel }
   * 
   * 
   */
  public List<LogLevel> getLogLevel() {
    if (logLevel == null) {
      logLevel = new ArrayList<LogLevel>(1);
    }
    return this.logLevel;
  }

  /**
   * Gets the value of the outputName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOutputName() {
    return outputName;
  }

  /**
   * Sets the value of the outputName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setOutputName(String value) {
    this.outputName = value;
  }

  @Override
  protected OutputConfiguration clone() {
    OutputConfiguration clone = new OutputConfiguration();
    clone.outputName = outputName;
    for (LogLevel level : getLogLevel()) {
      clone.getLogLevel().add(level.clone());
    }
    return clone;
  }

}
