<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modellingcore" nsURI="http://www.polarsys.org/capella/common/core/7.0.0"
    nsPrefix="org.polarsys.capella.common.data.core">
  <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
    <details key="profileName" value="ModellingCore"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
    <details key="trackResourceModification" value="true"/>
    <details key="useUUIDs" value="false"/>
    <details key="useIDAttributes" value="true"/>
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
    <details key="description" value="ModellingCore aims at defining the core concepts of any modelling language.&#xD;&#xA;[source: Capella study]"/>
    <details key="usage guideline" value="none"/>
    <details key="used in levels" value="operational,system,logical,physical,epbs"/>
    <details key="usage examples" value="none"/>
    <details key="constraints" value="none"/>
    <details key="comment/notes" value="none"/>
    <details key="reference documentation" value="none"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ExtensibleElement">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="ModelElement"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Element"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="common base for all Capella elements&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Element"/>
      <details key="constraints" value=""/>
    </eAnnotations>
    <eOperations name="destroy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="org.eclipse.emf.ecore.util.EcoreUtil.delete(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getFullLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.polarsys.capella.common.model.label.LabelRetriever.getFullLabel(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.polarsys.capella.common.model.label.LabelRetriever.getLabel(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="hasUnnamedLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.polarsys.capella.common.model.label.LabelRetriever.UNNAMED_ELEMENT.equals(this.getLabel());"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the unique identifier for this element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value=""/>
        <details key="constraints" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the unique system identifier for this element"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//AbstractConstraint" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of constraints applying to this element of the model&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Opposite reference of uml::Constraint::constrainedElement"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="constrainedElements"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConstraints" upperBound="-1"
        eType="#//AbstractConstraint" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the constraints that are stored/owned by this element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::nearestpackage"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Some packaged elements of uml::Element::nearestPackage on which AbstractConstraint stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMigratedElements"
        upperBound="-1" eType="#//ModelElement" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Temporary migrated elements for the purpose of model migration."/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRelationship" abstract="true"
      eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="Relationship"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Element"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Ignore"/>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="A relationship references one or more related elements. Relationship is an abstract metaclass&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Relationship"/>
      <details key="constraints" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedFlow" eType="#//AbstractInformationFlow"
        eOpposite="#//AbstractInformationFlow/realizations">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the information flow that this relationship realizes&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Opposite reference of uml::InformationFlow::realization"/>
        <details key="constraints" value="Multiplicity must be [0..1]"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNamedElement" abstract="true"
      eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="AbstractNamedElement"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="AbstractNamedElement"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="A named element represents elements that may have a name. The name is used for identification of the named element&#xD;&#xA;within the namespace in which it is defined. A named element also has a qualified name that allows it to be&#xD;&#xA;unambiguously identified within a hierarchy of nested namespaces. NamedElement is an abstract metaclass.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="- If there is no name, or one of the containing namespaces has no name, there is no qualified name.&#xD;&#xA;- When there is a name, and all of the containing namespaces have a name, the qualified name is constructed from the names of the containing namespaces.&#xD;&#xA;- If a NamedElement is not owned by a Namespace, it does not have a visibility.&#xD;&#xA;[source: Capella study]"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::NamedElement"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="name"/>
        <details key="featureOwner" value="AbstractNamedElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="namingAttribute" value="true"/>
        <details key="Label" value="name"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="The name of the NamedElement&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::NamedElement::name"/>
        <details key="explanation" value=""/>
        <details key="constraints" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformationsExchanger" abstract="true"
      eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="a model element that is the source and/or destination of information flows&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::NamedElement in order to map Capella AbstractInformationFlow::source and  AbstractInformationFlow::target to uml::InformationFlow::source and uml::InformationFlow::target"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingInformationFlows"
        upperBound="-1" eType="#//AbstractInformationFlow" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="list of information flows coming towards this element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Opposite reference of uml::InformationFlow::informationSource"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="target"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingInformationFlows"
        upperBound="-1" eType="#//AbstractInformationFlow" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="list of information flows coming out of this element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Opposite reference of uml::InformationFlow::informationTarget"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="source"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="informationFlows" upperBound="-1"
        eType="#//AbstractInformationFlow" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="patternbody"/>
        <details key="viatra.expression" value="AbstractInformationFlow.source(target, self);&#xD;&#xA;} or {&#xD;&#xA;&#x9;AbstractInformationFlow.target(target, self);"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceableElement" abstract="true" interface="true"
      eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="TraceableElement"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Element"/>
      <details key="stereotype" value="eng.TraceableElement"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Base abstract class supporting the ability to trace a model element to/from other elements&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::NamedElement"/>
      <details key="constraints" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTraces" upperBound="-1"
        eType="#//AbstractTrace" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="clientDependency"/>
        <details key="featureOwner" value="NamedElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="incomingTraces"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="targetElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of trace relationships pointing towards this element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and Transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTraces" upperBound="-1"
        eType="#//AbstractTrace" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="umlOppositeReference" value="supplier"/>
        <details key="umlOppositeReferenceOwner" value="Dependency"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="outgoingTraces"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="sourceElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of trace relationships starting from this element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and Transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalizableElement" abstract="true"
      eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="none"/>
      <details key="constraints" value="none"/>
      <details key="type" value="n/a"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="none"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublishableElement" abstract="true"
      eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="none"/>
      <details key="constraints" value="none"/>
      <details key="type" value="n/a"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibleInDoc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="none"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibleInLM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="none"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType" abstract="true" eSuperTypes="#//AbstractNamedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="base abstract class supporting the definition of data types&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Type"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractTypedElements"
        upperBound="-1" eType="#//AbstractTypedElement" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="abstractType"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of typed elements that reference this type&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and Transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTypedElement" abstract="true"
      eSuperTypes="#//AbstractNamedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="a (named) model element to which a specific type is associated&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::TypedElement"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractType" eType="#//AbstractType">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="type"/>
        <details key="featureOwner" value="TypedElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="type"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the type associated to this model element&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::TypedElement::type"/>
        <details key="explanation" value=""/>
        <details key="constraints" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTrace" abstract="true" interface="true"
      eSuperTypes="#//TraceableElement">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="AbstractTrace"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Dependency"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Ignore"/>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="abstract base class supporting the ability to define a trace relationship between two model elements&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Dependency"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" lowerBound="1"
        eType="#//TraceableElement">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="supplier"/>
        <details key="featureOwner" value="Dependency"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="target"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the target/end of the trace link&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Dependency::supplier"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Dependency::supplier elements on which TraceableElement stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Multiplicity must be [1..1]&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" lowerBound="1"
        eType="#//TraceableElement">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="client"/>
        <details key="featureOwner" value="Dependency"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="source"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the source/beginning of the trace link&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Dependency::client"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Dependency::client elements on which TraceableElement stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Multiplicity must be [1..1]"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConstraint" abstract="true"
      interface="true" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="specifies a constraint applying to a given set of model elements&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="n/a"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="The value specification for a constraint must evaluate to a Boolean value.&#xD;&#xA;&#xD;&#xA;Evaluating the value specification for a constraint must not have side effects&#xD;&#xA;&#xD;&#xA;A constraint cannot be applied to itself."/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Constraint"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedElements" upperBound="-1"
        eType="#//ModelElement">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the model elements being involved in the definition of this constraint&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Constraint::constrainedElement"/>
        <details key="explanation" value=""/>
        <details key="constraints" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSpecification" eType="#//ValueSpecification"
        containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="A condition that must be true when evaluated in order for the constraint to be satisfied"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ModelElement"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="opposite"/>
        <details key="viatra.expression" value="ownedConstraints"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Specifies the element that is the context for evaluating this constraint, which is the Constraint's parent element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"
      interface="true" eSuperTypes="#//AbstractTypedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="A value specification is the specification of a (possibly empty) set of instances, including both objects and data values&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="n/a"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::ValueSpecification,uml::InstanceSpecification&#xD;&#xA;uml::InstanceSpecification in order to map Capella AbstractParameter::rate to SysML::Activities::Rate"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractParameter" abstract="true" eSuperTypes="#//AbstractTypedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="A parameter is a specification of an argument used to pass information into or out of an invocation of a behavioral&#xD;&#xA;feature.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a (Abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical,epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="- A parameter cannot be a stream and exception at the same time.&#xD;&#xA;- An input parameter cannot be an exception.&#xD;&#xA;- Reentrant behaviors cannot have stream parameters.&#xD;&#xA;- Only in and inout parameters may have a delete effect. Only out, inout, and return parameters may have a create effect.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Parameter"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isException" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Tells whether an output parameter may emit a value to the exclusion of the other outputs&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Parameter::isException"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStream" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Tells whether an input parameter may accept values while its behavior is executing, or whether an output parameter&#xD;&#xA;post values while the behavior is executing&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Parameter::isStream"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="specifies whether the parameter is optional or not&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="n/a"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Capella AbstractParameter::isOptional is true if stereotype SysML::Activities::Optional is applied, false if not applied"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfRate" eType="#//RateKind">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="refer to RateKind enumeration description&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="refer to RateKind enumeration definition&#xD;&#xA;[source: Capella study]"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Capella AbstractParameter::kindOfRate is Capella RateKind::Continuous if stereotype SysML::Activities::Continuous is applied&#xD;&#xA;Capella AbstractParameter::kindOfRate is Capella RateKind::Discrete if stereotype SysML::Activities::Discrete is applied&#xD;&#xA;If none is applied, Capella AbstractParameter::kindOfRate is Capella RateKind::Unspecified"/>
        <details key="constraints" value="Applied stereotype that inherits from SysML::Activities::Rate stereotype must be either SysML::Activities::Continuous or SysML::Activities::Discrete.&#xD;&#xA;If none of both stereotypes are applied, kindOfRate is considered Unspecified"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" eType="#//ParameterEffectKind">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Specifies the effect that the owner of the parameter has on values passed in or out of the parameter&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="see ParameterEffectKind definition"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Parameter::effect"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate" eType="#//ValueSpecification"
        containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the number of objects or values that flow in or out of the parameter per time interval while the behavior or operation is executing&#xD;&#xA;[source: SysML specification v1.1]"/>
        <details key="constraints" value="this field only makes sense if the parameter is a streaming one.&#xD;&#xA;[source: SysML specification v1.1]"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::specific"/>
        <details key="explanation" value="SysML::Activities::Probability does not extend uml::Parameter"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" eType="#//ValueSpecification"
        containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Likelihood that values will be output on a parameter set&#xD;&#xA;[source: SysML specification v1.1]"/>
        <details key="constraints" value="the probability should be a number between 0 and 1"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::specific"/>
        <details key="explanation" value="SysML::Activities::Probability does not extend uml::Parameter"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterSet" upperBound="-1"
        eType="#//AbstractParameterSet" eOpposite="#//AbstractParameterSet/parameters">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="The parameter sets containing the parameter. See AbstractParameterSet&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Parameter::parameterSet"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterEffectKind">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="The datatype ParameterEffectKind is an enumeration that indicates the effect of a behavior on values passed in or out of&#xD;&#xA;its parameters&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value="uml::ParameterEffectKind"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eLiterals name="create" value="2">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="referenced parameter value is being created upon behavior execution&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::ParameterEffectKind::create"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="read">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="referenced parameter value is only being read upon behavior execution&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::ParameterEffectKind::read"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="update" value="1">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="referenced parameter value is being updated upon behavior execution&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::ParameterEffectKind::update"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="delete" value="3">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="referenced parameter value is being deleted upon behavior execution&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::ParameterEffectKind::delete"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractParameterSet" abstract="true"
      eSuperTypes="#//AbstractNamedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="A parameter set is an element that provides alternative sets of inputs or outputs that a behavior may use.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="n/a"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="- The parameters in a parameter set must all be inputs or all be outputs of the same parameterized entity, and the parameter set is owned by that entity.&#xD;&#xA;- If a behavior has input parameters that are in a parameter set, then any inputs that are not in a parameter set must be streaming. Same for output parameters.&#xD;&#xA;- Two parameter sets cannot have exactly the same set of parameters.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::ParameterSet"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConditions" upperBound="-1"
        eType="#//AbstractConstraint" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Constraint that should be satisfied for the owner of the parameters in an input parameter set to start execution using&#xD;&#xA;the values provided for those parameters, or the owner of the parameters in an output parameter set to end execution&#xD;&#xA;providing the values for those parameters, if all preconditions and conditions on input parameter sets were satisfied&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::ParameterSet::condition"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" eType="#//ValueSpecification"
        containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the probability the parameter set will be given values at runtime&#xD;&#xA;[source: SysML specification v1.1]"/>
        <details key="constraints" value="These must be between zero and one inclusive, and add up to one for output parameter sets of the&#xD;&#xA;same behavior at the time the probabilities are used.&#xD;&#xA;[source: SysML specification v1.1]"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::specific"/>
        <details key="explanation" value="If SysML::Activities::Probability stereotype is applied, Capella AbstractParameterSet::probability is equal to SysML::Activities::Probability::probability."/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//AbstractParameter" eOpposite="#//AbstractParameter/parameterSet">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Parameters in the parameter set.&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::ParameterSet::parameter"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RateKind">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="enumeration containing the possible caracterizations for the rate of a streaming parameter&#xD;&#xA;[source: Capella study]"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value="keyword::none"/>
      <details key="explanation" value="Stereotype that inherits from SysML::Activities::Rate (SysML::Activities::Continuous or SysML::Activities::Discrete)"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eLiterals name="Unspecified">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the rate kind is not precised&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="Neither SysML::Activities::Continuous or SysML::Activities::Discrete stereotypes are applied"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Continuous" value="1">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the rate characterizes a continuous flow&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="SysML::Activities::Continuous"/>
        <details key="explanation" value="SysML::Activities::Continuous stereotype is applied"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Discrete" value="2">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Used when the rate characterizes a discrete flow&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="SysML::Activities::Discrete"/>
        <details key="explanation" value="SysML::Activities::Discrete"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInformationFlow" abstract="true"
      eSuperTypes="#//AbstractNamedElement #//AbstractRelationship">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="An InformationFlow specifies that one or more information items circulates from its sources to its targets. Information&#xD;&#xA;flows require some kind of 'information channel' for transmitting information items from the source to the destination.&#xD;&#xA;An information channel is represented in various ways depending on the nature of its sources and targets.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="n/a"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::InformationFlow"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizations" upperBound="-1"
        eType="#//AbstractRelationship" eOpposite="#//AbstractRelationship/realizedFlow">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Determines which Relationship will realize the specified flow.&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::InformationFlow::realization"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="convoyedInformations" upperBound="-1"
        eType="#//AbstractExchangeItem">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Specifies the information items that may circulate on this information flow&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::InformationFlow::conveyed"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Order will not be preserved"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//InformationsExchanger">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Defines from which source the conveyed information items are initiated&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::InformationFlow::informationSource"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Multiplicity must be [0..1]"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//InformationsExchanger">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Defines to which target the conveyed information items are directed&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::InformationFlow::informationTarget"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="Multiplicity must be [0..1]"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExchangeItem" abstract="true"
      eSuperTypes="#//AbstractType">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Set of exchanged element (e.g. data, material...) expected or provided, exchanged between ports"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="n/a"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Classifier in order to map Capella AbstractInformationFlow::convoyedInformations to uml::InformationFlow::conveyed."/>
      <details key="constraints" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IState" abstract="true" interface="true"
      eSuperTypes="#//AbstractNamedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="A vertex is an abstraction of a node in a state machine graph. In general, it can be the source or destination of any number&#xD;&#xA;of transitions.&#xD;&#xA;[source:UML Superstructure v2.2]"/>
      <details key="usage guideline" value="n/a (abstract)"/>
      <details key="used in levels" value="operational,system,logical,physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value=""/>
      <details key="explanation" value="uml::Vertex"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedStates" upperBound="-1"
        eType="#//IState">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="none"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exploitedStates" upperBound="-1"
        eType="#//IState">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="none"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
