<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epbs" nsURI="http://www.polarsys.org/capella/core/epbs/7.0.0"
    nsPrefix="org.polarsys.capella.core.data.epbs">
  <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
    <details key="trackResourceModification" value="true"/>
    <details key="useUUIDs" value="false"/>
    <details key="useIDAttributes" value="true"/>
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
    <details key="description" value="(E)PBS (for (End-)Product Breakdown Structure) aims at defining the system's work product breakdown (close to Clearcase/UCM's components concept).&#xD;&#xA;[source: Capella study]"/>
    <details key="usage guideline" value="none"/>
    <details key="used in levels" value="epbs"/>
    <details key="usage examples" value="none"/>
    <details key="constraints" value="This package depends on the model CompositeStructure.ecore"/>
    <details key="comment/notes" value="none"/>
    <details key="reference documentation" value="none"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
  <eClassifiers xsi:type="ecore:EClass" name="EPBSArchitecturePkg" eSuperTypes="CompositeStructure.ecore#//BlockArchitecturePkg">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="EPBSArchitecturePkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Package"/>
      <details key="stereotype" value="eng.sys.EPBSArchitecturePkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Package that contains end product breakdown structure architectures&#xD;&#xA;[source:Capella study]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEPBSArchitectures"
        upperBound="-1" eType="#//EPBSArchitecture" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedEPBSArchitectures"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="End product breakdown structure architectures set&#xD;&#xA;[source:Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which EPBSArchitecture stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPBSArchitecture" eSuperTypes="CompositeStructure.ecore#//ComponentArchitecture">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="EPBSArchitecture"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Package"/>
      <details key="stereotype" value="eng.sys.EPBSArchitecture"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="End Product Breakdown Structure. Definition of the Physical Components grouping for development subcontracting or purchase. "/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItemPkg"
        eType="#//ConfigurationItemPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedConfigurationItemPkgs"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Set of packages that contain configuration items, owned by this EPBS architecture&#xD;&#xA;[source:Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which ConfigurationItemPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedCapabilityRealizationPkg"
        eType="ecore:EClass LogicalArchitecture.ecore#//CapabilityRealizationPkg"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedAbstractCapabilityPkg"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="feature" value="ownedAbstractCapabilityPkg"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalArchitectureRealizations"
        upperBound="-1" eType="#//PhysicalArchitectureRealization" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Set of physical architecture realization links owned by this EPBS architecture&#xD;&#xA;[source:Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which PhysicalArchitectureRealisation stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalArchitectureRealizations"
        upperBound="-1" eType="#//PhysicalArchitectureRealization" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="provisionedArchitectureAllocations"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="(automatically computed) the physical architecture realization links involving this EPBS architecture&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalArchitectures"
        upperBound="-1" eType="ecore:EClass PhysicalArchitecture.ecore#//PhysicalArchitecture"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="PhysicalArchitecture.ecore#//PhysicalArchitecture/allocatingEpbsArchitectures">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="allocatedArchitectures"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationItemPkg" eSuperTypes="CompositeStructure.ecore#//ComponentPkg">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="ConfigurationItemPkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Package"/>
      <details key="stereotype" value="eng.sys.ConfigurationItemPkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Package that contains configuration item elements&#xD;&#xA;[source:Capella study]"/>
      <details key="usage guideline" value="this element is provided as a utility to better structure configuration items, if needed"/>
      <details key="used in levels" value="epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItems"
        upperBound="-1" eType="#//ConfigurationItem" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedConfigurationItems"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Set of configuration items that are stored in the package&#xD;&#xA;[source:Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which ConfigurationItem stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItemPkgs"
        upperBound="-1" eType="#//ConfigurationItemPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedConfigurationItemPkgs"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Set of owned packages containing configuration items&#xD;&#xA;[source:Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which ConfigurationItemPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationItem" eSuperTypes="CapellaCommon.ecore#//CapabilityRealizationInvolvedElement CompositeStructure.ecore#//Component">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="ConfigurationItem"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Component"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Aggregation of hardware, software, processed materials, services, or any of their discrete portions designated for configuration management and treated as a single entity in the configuration management process."/>
      <details key="usage guideline" value="A configuration item is an abstract concept. Concrete concepts are : COTCI, CSCI, HWCI, InterfaceCI, NDICI, PrimeItemCI and SystemCI"/>
      <details key="used in levels" value="epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
      <details key="arcadia_description" value="A configuration item (CI) is a part of the system, to be &#xD;&#xA;- Designed and produced, or purchased&#xD;&#xA;- Duplicated as much as it is used in the system&#xD;&#xA;- assembled with others &#xD;&#xA;in order to build each copy of the system. &#xD;&#xA;Examples of configuration items are cabinets, racks, electronic boards, wiring &amp; plugs, software components...&#xD;&#xA;CI are usually qualified as Hardware (HWCI), Computer Software (CSCI), Commercial off the Shelf (COTS, purchased item), Prime Item...&#xD;&#xA;"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="SysML::Blocks::Block"/>
      <details key="explanation" value="Could have been mapped to Package (to be closer to the semantic of a &quot;group of&quot; physical components, &#xD;&#xA;but it is not possible since there are Parts associated to CI's, and packages do not inherit from Type, hence cannot be used to type a Part."/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ConfigurationItemKind"
        defaultValueLiteral="Unset">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItems"
        upperBound="-1" eType="#//ConfigurationItem" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Component"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedConfigurationItems"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the children of this ConfigurationItem &#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Class::nestedClassifier"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Class::nestedClassifier elements on which ConfigurationItem stereotype or any stereotype that inherits from it is applied"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItemPkgs"
        upperBound="-1" eType="#//ConfigurationItemPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Component"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedConfigurationItemPkgs"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the sub-(configuration item) packages owned by this component"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::nearestpackage"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="store them in the nearest possible package, since a Block cannot contain packages"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalArtifactRealizations"
        upperBound="-1" eType="#//PhysicalArtifactRealization" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Physical Artifact Realization links owned by this Configuration Item"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalArtifacts"
        ordered="false" upperBound="-1" eType="ecore:EClass CompositeStructure.ecore#//AbstractPhysicalArtifact"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="CompositeStructure.ecore#//AbstractPhysicalArtifact/allocatorConfigurationItems">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="patternbody"/>
        <details key="viatra.expression" value="PhysicalArtifactRealization.sourceElement(par, self);&#xD;&#xA;PhysicalArtifactRealization.targetElement(par, target);"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="(automatically computed) the list of realizations links coming from physical artifacts, and in which this ConfigurationItem is involved&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConfigurationItemKind">
    <eLiterals name="Unset"/>
    <eLiterals name="COTSCI" value="1">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Commercial Off The Shelves Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CSCI" value="2">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Computer Software Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HWCI" value="3">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Hardware Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="InterfaceCI" value="4">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Interface Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NDICI" value="5">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Non Developmental Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PrimeItemCI" value="6">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Prime Item Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SystemCI" value="7">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="System Configuration Item"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="epbs"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalArchitectureRealization" eSuperTypes="CompositeStructure.ecore#//ArchitectureAllocation">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Realization link betwen an EPBS architecture and a physical architecture&#xD;&#xA;[source:Capella study]&#xD;&#xA;&#xD;&#xA;Realization is a specialized abstraction relationship between two sets of model elements, one representing a specification&#xD;&#xA;(the supplier) and the other represents an implementation of the latter (the client). Realization can be used to model&#xD;&#xA;stepwise refinement, optimizations, transformations, templates, model synthesis, framework composition, etc.&#xD;&#xA;[source: UML superstructure v2.2]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="epbs"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Realization"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalArtifactRealization" eSuperTypes="CapellaCore.ecore#//Allocation">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Realization link betwen a Configuration Item and a physical artifact"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedPhysicalArtifact"
        lowerBound="1" eType="ecore:EClass CompositeStructure.ecore#//AbstractPhysicalArtifact"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="targetElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Specifies the allocated architecture&#xD;&#xA;[source: Capella study]&#xD;&#xA;&#xD;&#xA;Specifies the targets of the DirectedRelationship.&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizingConfigurationItem"
        lowerBound="1" eType="#//ConfigurationItem" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="sourceElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="Specifies the allocating architecture&#xD;&#xA;[source: Capella study]&#xD;&#xA;&#xD;&#xA;Specifies the sources of the DirectedRelationship.&#xD;&#xA;[source: UML superstructure v2.2]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
