<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pa" nsURI="http://www.polarsys.org/capella/core/pa/7.0.0" nsPrefix="org.polarsys.capella.core.data.pa">
  <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
    <details key="trackResourceModification" value="true"/>
    <details key="useUUIDs" value="false"/>
    <details key="useIDAttributes" value="true"/>
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
    <details key="description" value="PhysicalArchitecture aims at defining the system's software, middleware and hardware architecture modelling language (close to the OMG's Platform Independent Model (PIM) in addition to OMG's Platform Model (PM)) using notions close to OMG's MARTE Resource concept. It adds the Deployment concern.&#xD;&#xA;This concern aggregates a lot of concepts regarding the others. A re-engineering of this concern should make sense.&#xD;&#xA;[source: Capella study]"/>
    <details key="usage guideline" value="none"/>
    <details key="used in levels" value="physical"/>
    <details key="usage examples" value="none"/>
    <details key="constraints" value="This package depends on the model CompositeStructure.ecore"/>
    <details key="comment/notes" value="none"/>
    <details key="reference documentation" value="none"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalArchitecturePkg" eSuperTypes="CompositeStructure.ecore#//BlockArchitecturePkg">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="PhysicalArchitecturePkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Package"/>
      <details key="stereotype" value="eng.PhysicalArchitecturePkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="container for physical architecture elements&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalArchitecturePkgs"
        upperBound="-1" eType="#//PhysicalArchitecturePkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="subPhysicalArchitecturePkgs"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="sub-(physical architecture) packages contained in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which PhysicalArchitecturePkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalArchitectures"
        upperBound="-1" eType="#//PhysicalArchitecture" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedPhysicalArchitectures"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the physical architecture elements contained in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which PhysicalArchitecture stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalArchitecture" eSuperTypes="CompositeStructure.ecore#//ComponentArchitecture">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="Physical Architecture"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Package"/>
      <details key="stereotype" value="eng.PhysicalArchitecture"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Model describing physical architecture part - hardware components &amp; related items -  associated to (created during) a modelling phase"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponentPkg"
        eType="#//PhysicalComponentPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedComponentPkgs"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="a package containing the physical components involved in this physical architecture&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which PhysicalComponentPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Multiplicity must be [0..1]"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedCapabilityRealizationPkg"
        eType="ecore:EClass LogicalArchitecture.ecore#//CapabilityRealizationPkg"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedAbstractCapabilityPkg"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="feature" value="ownedAbstractCapabilityPkg"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPhysicalFunctionPkg"
        eType="#//PhysicalFunctionPkg" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedFunctionPkg"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="feature" value="ownedFunctionPkg"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeployments" upperBound="-1"
        eType="ecore:EClass CompositeStructure.ecore#//AbstractDeploymentLink" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedDeployments"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the various deployments associated with this physical architecture&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which AbstractDeployment stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalArchitectureRealizations"
        upperBound="-1" eType="#//LogicalArchitectureRealization" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of a relationships between physical architectures and the logical architectures that they realize, stored/owned by this architecture&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which LogicalArchitectureRealisation stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedLogicalArchitectureRealizations"
        upperBound="-1" eType="#//LogicalArchitectureRealization" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="clientDependency"/>
        <details key="featureOwner" value="NamedElement"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="allocatedLogicalArchitectureImplementations"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="derive" value="self.ownedPartitions.representedElement.oclIsKindOf(PhysicalComponent) -> oclAsType(PhysicalComponent)"/>
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="provisionedArchitectureAllocations"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of relationships between this physical architecture and the logical architectures to which it is allocated&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedLogicalArchitectures"
        upperBound="-1" eType="ecore:EClass LogicalArchitecture.ecore#//LogicalArchitecture"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="LogicalArchitecture.ecore#//LogicalArchitecture/allocatingPhysicalArchitectures">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="allocatedArchitectures"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatingEpbsArchitectures"
        upperBound="-1" eType="ecore:EClass EPBSArchitecture.ecore#//EPBSArchitecture"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="EPBSArchitecture.ecore#//EPBSArchitecture/allocatedPhysicalArchitectures">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="allocatingArchitectures"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalFunction" eSuperTypes="FunctionalAnalysis.ecore#//AbstractFunction">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Function applied at physical level&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="this element is used in the &quot;functional approach&quot; usage, as the result of the flow down/refinement of the functions at the logical architecture level&#xD;&#xA;[source: Capella study]"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="../img/usage_examples/example_physical_functions.png"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Activity"/>
      <details key="explanation" value="All functions are mapped to (empty) activities"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalFunctionPkgs"
        upperBound="-1" eType="#//PhysicalFunctionPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the sub-(physical function) packages contained in this physical function"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which PhysicalFunctionPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatingPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" changeable="false" volatile="true"
        transient="true" derived="true" eOpposite="#//PhysicalComponent/allocatedPhysicalFunctions">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="patternbody"/>
        <details key="viatra.expression" value="PhysicalFunction.incomingTraces(self, incomingTraces);&#xD;&#xA;ComponentFunctionalAllocation.sourceElement(incomingTraces, target);"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedLogicalFunctions"
        upperBound="-1" eType="ecore:EClass LogicalArchitecture.ecore#//LogicalFunction"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="LogicalArchitecture.ecore#//LogicalFunction/realizingPhysicalFunctions">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="outFunctionRealizations.allocatedFunction"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedFunctions"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="feature" value="ownedFunctions"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="subFunctions"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="list of children physical functions&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalFunctionPkg" eSuperTypes="FunctionalAnalysis.ecore#//FunctionPkg">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="container for physical functions&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="Used to structure the storage of physical function elements inside a physical architecture&#xD;&#xA;"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the physical functions contained in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which PhysicalFunction stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalFunctionPkgs"
        upperBound="-1" eType="#//PhysicalFunctionPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the sub-(physical function) packages contained in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which PhysicalFunctionPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalComponent" eSuperTypes="CompositeStructure.ecore#//AbstractPhysicalArtifact CompositeStructure.ecore#//Component CapellaCommon.ecore#//CapabilityRealizationInvolvedElement CompositeStructure.ecore#//DeployableElement CompositeStructure.ecore#//DeploymentTarget">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="PhysicalComponent"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Component"/>
      <details key="stereotype" value="eng.PhysicalComponent"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="Physical Components are the artifacts enabling to describe architectural solutions to satisfy the logical architecture identified at the upper abstraction level. Physical components are identified according to physical rationals (i.e. components reuse, available COTS, non functional constraints...)&#xD;&#xA;Examples: Software component, executable, hardware component (mechanical devices, electronical boards, equipments)"/>
      <details key="usage guideline" value="refer to description"/>
      <details key="arcadia_description" value="Physical Components are the artefacts enabling to describe the final physical decomposition of the system. Physical components are identified according to physical and development constraints.&#xD;&#xA;Two kinds of physical components exist: behavioural and implementation components.&#xD;&#xA;Two kinds of physical components are identified:&#xD;&#xA;- A behavioural component is a physical component in charge of implementing / realising part of the functions allocated to the system&#xD;&#xA;Example: software component, VHDL program (for a programmable device), hardware selector...&#xD;&#xA;- An implementation component  is a material physical component, resource embedding some behavioural components, and necessary to their expected behaviour.&#xD;&#xA;Example: Hardware computing board, computer, FPGA (programmable device), ...&#xD;&#xA;"/>
      <details key="usage examples" value="../img/usage_examples/example_physical_components.png"/>
      <details key="used in levels" value="physical"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="SysML::Blocks::Block"/>
      <details key="explanation" value="cannot map to uml::Component, which is not part of UML4SysML"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//PhysicalComponentKind">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="type"/>
        <details key="fromStereotype" value="true"/>
        <details key="featureOwner" value="eng.AbstractPhysicalComponent"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="specifies the type of physical component (refer to PhysicalComponentKind for detailed description)&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="refer to PhysicalComponentKind definition"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//PhysicalComponentNature">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="specifies the nature of this physical component, typically whether it is an actual execution node, or a behavioral component like a SW part&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="type" value="refer to PhysicalComponentNature definition"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentLinks" upperBound="-1"
        eType="ecore:EClass CompositeStructure.ecore#//AbstractDeploymentLink" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the various deployments of this physical component&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::nearestpackage"/>
        <details key="explanation" value="SysML::Blocks::Block cannot contain AbstractDeployment's equivalent, hence we find the nearest available package to store them."/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the physical components stored under this component&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Class::nestedClassifier"/>
        <details key="explanation" value="the nesting relation is just convenient to store sub-components under a component in the three, even though the hierachical relationship between componenets is not&#xD;&#xA;derived from this nesting : instead, it relies on the Parts present in the component, that are typed by the sub-components types."/>
        <details key="constraints" value="uml::Class::nestedClassifier elements on which PhysicalComponent stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponentPkgs"
        upperBound="-1" eType="#//PhysicalComponentPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the sub-(physical component) packages owned by this component&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::nearestpackage"/>
        <details key="explanation" value="SysML::Blocks::Block cannot contain packages, hence we find the nearest available package to store them."/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalInterfaceRealizations"
        upperBound="-1" eType="#//LogicalInterfaceRealization" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="provisionedInterfaceAllocations"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the list of logical interfaces that this physical component reallizes&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="subActors"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedPartitions.type"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the children components of this physical component&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedLogicalComponents"
        ordered="false" upperBound="-1" eType="ecore:EClass LogicalArchitecture.ecore#//LogicalComponent"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="LogicalArchitecture.ecore#//LogicalComponent/realizingPhysicalComponents">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="patternbody"/>
        <details key="viatra.expression" value="PhysicalComponent.outgoingTraces(self, lcr);&#xD;&#xA;&#x9;LogicalComponentRealization.targetElement(lcr, target);"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="(automatically computed) the list of realizations links coming from logical components, and in which this physical component is involved&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction" changeable="false" volatile="true"
        transient="true" derived="true" eOpposite="#//PhysicalFunction/allocatingPhysicalComponents">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="allocatedFunctions"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="patternbody"/>
        <details key="viatra.expression" value="Part.abstractType(part, self);&#xD;&#xA;&#x9;Part.deploymentLinks.deployedElement(part, deployedPart);&#xD;&#xA;&#x9;Part.abstractType(deployedPart, target);&#xD;&#xA;} or {&#xD;&#xA;&#x9;Part.abstractType(part, self);&#xD;&#xA;&#x9;Part.deploymentLinks.deployedElement(part, target);"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployingPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="patternbody"/>
        <details key="viatra.expression" value="Part.abstractType(part, self);&#xD;&#xA;&#x9;Part.deployingLinks.location(part, deployedPart);&#xD;&#xA;&#x9;Part.abstractType(deployedPart, target);&#xD;&#xA;} or {&#xD;&#xA;&#x9;Part.abstractType(part, self);&#xD;&#xA;&#x9;Part.deploymentLinks.deployedElement(part, target);"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalComponentPkg" eSuperTypes="CompositeStructure.ecore#//ComponentPkg Information.ecore#//AssociationPkg">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="PhysicalComponentPkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Package"/>
      <details key="stereotype" value="eng.PhysicalComponentPkg"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="a container for physical component entities&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedComponents"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the physical components stored in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which PhysicalComponent stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponentPkgs"
        upperBound="-1" eType="#//PhysicalComponentPkg" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="subPhysicalComponentPkgs"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the sub-(physical component) packages contained in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::nestedPackage elements on which PhysicalComponentPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedKeyParts" upperBound="-1"
        eType="ecore:EClass Information.ecore#//KeyPart" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedKeyParts"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the key parts contained in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which KeyPart stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeployments" upperBound="-1"
        eType="ecore:EClass CompositeStructure.ecore#//AbstractDeploymentLink" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="featureName" value="packagedElement"/>
        <details key="featureOwner" value="Package"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="ownedDeployments"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="the physical deployment definitions stored in this package&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="uml::Package::packagedElement elements on which AbstractDeployment stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalNode" eSuperTypes="#//PhysicalComponent">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="PhysicalNode"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="metaclass" value="Component"/>
      <details key="stereotype" value="eng.PhysicalNode"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="a physical resource hosting behavioral components, and required for their execution or expected behavior&#xD;&#xA;[source: Arcadia encyclopedia]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Node"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPhysicalNodes" upperBound="-1"
        eType="#//PhysicalNode" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="subActors"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
      <eAnnotations source="http://www.polarsys.org/capella/derived">
        <details key="viatra.variant" value="alias"/>
        <details key="viatra.expression" value="ownedPartitions.type"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="all derived children of this physical node&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value="keyword::none"/>
        <details key="explanation" value="Derived and transient"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic">
        <details key="excludefrom" value="xmlpivot"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalComponentKind">
    <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
      <details key="Label" value="PhysicalComponentType"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
      <details key="enum" value="PhysicalComponentType"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="allows to categorize a physical component, with respect to real life physical entities&#xD;&#xA;[source: Capella study]"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eLiterals name="UNSET">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component kind is not precised&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HARDWARE" value="1">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="HARDWARE"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a hardware resource&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HARDWARE_COMPUTER" value="2">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="HARDWARE_COMPUTER"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a computing resource&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SOFTWARE" value="3">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="SOFTWARE"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a software entity&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SOFTWARE_DEPLOYMENT_UNIT" value="4">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="SOFTWARE_DEPLOYMENT_UNIT"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a software deployment unit&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SOFTWARE_EXECUTION_UNIT" value="5">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="SOFTWARE_EXECUTION_UNIT"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a software execution unit&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SOFTWARE_APPLICATION" value="6">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="SOFTWARE_APPLICATION"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a software application&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FIRMWARE" value="7">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="FIRMWARE"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a firmware part&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PERSON" value="8">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="PERSON"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a person&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FACILITIES" value="9">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="FACILITIES"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component refers to Facilities&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DATA" value="10">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="DATA"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component represents a set of data&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MATERIALS" value="11">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="MATERIALS"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component represents a bunch of materials&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SERVICES" value="12">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="SERVICES"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical components represents a set of services&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PROCESSES" value="13">
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="enumLiteral" value="PROCESSES"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component represents a set of processes&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalArchitectureRealization" eSuperTypes="CompositeStructure.ecore#//ArchitectureAllocation">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="mediator class supporting the implementation of the allocation link between a physical architecture, and the logical architecture(s) that it realizes&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::Realization"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalInterfaceRealization" eSuperTypes="CompositeStructure.ecore#//InterfaceAllocation">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="mediator class supporting the implementation of the allocation link between a physical interface, and the logical interface(s) that it realizes&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="n/a"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="n/a"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="base metaclass in UML/SysML profile " value="uml::InterfaceRealization"/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalComponentNature">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="characterizes a physical component, with respect to its property of being a host of behavioral components, or a behavioral component&#xD;&#xA;[source: Capella study]"/>
      <details key="constraints" value="none"/>
      <details key="comment/notes" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
      <details key="UML/SysML semantic equivalences" value=""/>
      <details key="explanation" value="none"/>
      <details key="constraints" value="none"/>
    </eAnnotations>
    <eLiterals name="UNSET">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component nature is not precised&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BEHAVIOR" value="1" literal="BEHAVIOR">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component nature is behavioral (typically, a piece of software)&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NODE" value="2">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="used when the physical component is a host for behavioral components (typically, a computing resource)&#xD;&#xA;[source: Capella study]"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eSubpackages name="deployment" nsURI="http://www.polarsys.org/capella/core/pa/deployment/7.0.0"
      nsPrefix="org.polarsys.capella.core.data.pa.deployment">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
      <details key="trackResourceModification" value="true"/>
      <details key="useUUIDs" value="false"/>
      <details key="useIDAttributes" value="true"/>
      <details key="extensibleProviderFactory" value="true"/>
      <details key="childCreationExtenders" value="true"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description" value="PhysicalArchitecture aims at defining the system's software, middleware and hardware architecture modelling language (close to the OMG's Platform Independent Model (PIM) in addition to OMG's Platform Model (PM)) using notions close to OMG's MARTE Resource concept. It adds the Deployment concern.&#xD;&#xA;This concern aggregates a lot of concepts regarding the others. A re-engineering of this concern should make sense.&#xD;&#xA;[source: Capella study]"/>
      <details key="usage guideline" value="none"/>
      <details key="used in levels" value="physical"/>
      <details key="usage examples" value="none"/>
      <details key="constraints" value="This package depends on the model CompositeStructure.ecore"/>
      <details key="comment/notes" value="none"/>
      <details key="reference documentation" value="none"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="#//deployment/AbstractPhysicalInstance CompositeStructure.ecore#//DeployableElement CompositeStructure.ecore#//DeploymentTarget">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="An instance of a component for deployment purposes."/>
        <details key="usage guideline" value="none"/>
        <details key="used in levels" value="physical"/>
        <details key="usage examples" value="none"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="portInstances" upperBound="-1"
          eType="#//deployment/PortInstance" changeable="false" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.polarsys.org/capella/derived">
          <details key="viatra.variant" value="alias"/>
          <details key="viatra.expression" value="ownedAbstractPhysicalInstances"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value="keyword::none"/>
          <details key="explanation" value="Derived and transient"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAbstractPhysicalInstances"
          upperBound="-1" eType="#//deployment/AbstractPhysicalInstance" containment="true">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstanceDeploymentLinks"
          upperBound="-1" eType="#//deployment/InstanceDeploymentLink" containment="true">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//PhysicalComponent">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectionInstance" eSuperTypes="#//deployment/AbstractPhysicalInstance">
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectionEnds" upperBound="-1"
          eType="#//deployment/PortInstance" eOpposite="#//deployment/PortInstance/connections">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic">
          <details key="excludefrom" value="xmlpivot"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass FunctionalAnalysis.ecore#//ComponentExchange">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentAspect" eSuperTypes="CapellaCore.ecore#//Structure">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="DeploymentAspect"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="metaclass" value="Package"/>
        <details key="stereotype" value="eng.DeploymentAspect"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="a grouping of deployment configurations, with a specific applicative meaning&#xD;&#xA;[source: Capella study]"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="physical"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurations"
          upperBound="-1" eType="#//deployment/DeploymentConfiguration" containment="true">
        <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
          <details key="featureName" value="packagedElement"/>
          <details key="featureOwner" value="Package"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
          <details key="Label" value="ownedConfigurations"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
        <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
          <details key="description" value="the deployment configurations associated to this deployment aspect&#xD;&#xA;[source: Capella study]"/>
          <details key="constraints" value="none"/>
          <details key="comment/notes" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value="uml::Package::packagedElement"/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="uml::Package::packagedElement elements on which DeploymentConfiguration stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentAspects"
          upperBound="-1" eType="#//deployment/DeploymentAspect" containment="true"
          resolveProxies="false">
        <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
          <details key="featureName" value="packagedElement"/>
          <details key="featureOwner" value="Package"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
          <details key="Label" value="ownedAspects"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/2007/ImpactAnalysis/Segment"/>
        <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
          <details key="description" value="the sub packages contained under this package&#xD;&#xA;[source: Capella study]"/>
          <details key="constraints" value="none"/>
          <details key="comment/notes" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value="uml::Package::nestedPackage#uml::Package::packagedElement"/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="uml::Package::nestedPackage elements on which AbstractCapabilityPkg stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentConfiguration" eSuperTypes="CapellaCore.ecore#//NamedElement">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="DeploymentConfiguration"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="metaclass" value="Package"/>
        <details key="stereotype" value="eng.DeploymentConfiguration"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="a consistent set of deployment specifications&#xD;&#xA;[source: Capella study]"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="physical"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value="uml::Package"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentLinks"
          upperBound="-1" eType="ecore:EClass CompositeStructure.ecore#//AbstractDeploymentLink"
          containment="true">
        <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
          <details key="featureName" value="elementImport"/>
          <details key="featureOwner" value="Namespace"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
          <details key="Label" value="deployments"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
          <details key="description" value="the deployment specifications that are part of this deployment configuration&#xD;&#xA;[source: Capella study]"/>
          <details key="constraints" value="none"/>
          <details key="comment/notes" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value="uml::Namespace::elementImport"/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="uml::Namespace::elementImport elements on which AbstractDeployment stereotype or any stereotype that inherits from it is applied&#xD;&#xA;Order must be computed"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalInstances"
          upperBound="-1" eType="#//deployment/AbstractPhysicalInstance" containment="true">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceDeploymentLink" eSuperTypes="CompositeStructure.ecore#//AbstractDeploymentLink">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="InstanceDeploymentLink"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="metaclass" value="Dependency"/>
        <details key="stereotype" value="eng.InstanceDeploymentLink"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="link between a physical object and its deployment element&#xD;&#xA;[source: Capella study]"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="n/a"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="n/a"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value="uml::Dependency"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PartDeploymentLink" eSuperTypes="CompositeStructure.ecore#//AbstractDeploymentLink">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="PartDeploymentLink"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="metaclass" value="Dependency"/>
        <details key="stereotype" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="link between a part and its deployment element"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="n/a"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="n/a"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value="uml::Dependency"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalInstance" abstract="true"
        eSuperTypes="CapellaCore.ecore#//CapellaElement">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="PhysicalObject"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="metaclass" value="InstanceSpecification"/>
        <details key="stereotype" value="eng.PhysicalObject"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="an instance of a physical component&#xD;&#xA;[source: Capella study]"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="physical"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortInstance" eSuperTypes="#//deployment/AbstractPhysicalInstance">
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value=""/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
          eType="#//deployment/ConnectionInstance" eOpposite="#//deployment/ConnectionInstance/connectionEnds">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//deployment/ComponentInstance" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.polarsys.org/capella/derived">
          <details key="viatra.variant" value="opposite"/>
          <details key="viatra.expression" value="portInstances"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value="keyword::none"/>
          <details key="explanation" value="Derived and transient"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass FunctionalAnalysis.ecore#//ComponentPort">
        <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
          <details key="UML/SysML semantic equivalences" value=""/>
          <details key="explanation" value="none"/>
          <details key="constraints" value="none"/>
        </eAnnotations>
        <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeploymentLink" eSuperTypes="CompositeStructure.ecore#//AbstractDeploymentLink">
      <eAnnotations source="http://www.polarsys.org/capella/2007/BusinessInformation">
        <details key="Label" value="TypeDeploymentLink"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/2007/UML2Mapping">
        <details key="metaclass" value="Dependency"/>
        <details key="stereotype" value="eng.TypeDeploymentLink"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description" value="deployment link between a data type and the model element that deploys it&#xD;&#xA;[source: Capella study]"/>
        <details key="usage guideline" value="n/a"/>
        <details key="used in levels" value="n/a"/>
        <details key="usage examples" value="n/a"/>
        <details key="constraints" value="none"/>
        <details key="comment/notes" value="none"/>
        <details key="reference documentation" value="none"/>
      </eAnnotations>
      <eAnnotations source="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping">
        <details key="UML/SysML semantic equivalences" value=""/>
        <details key="base metaclass in UML/SysML profile " value="uml::Dependency"/>
        <details key="explanation" value="none"/>
        <details key="constraints" value="none"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
